### ISSUE TITLE
Port to BRCore or Implementation under Forged?

### ISSUE THREAD

**Issue by NotJustAnna** [TheBrazillianForgersTeam/ArchitectFriend#1]
Forged is turning to be "The Mini-Mod Mega-Mod of the Team". Should we pass Architect to BRCore, to Forged, or to remove this mod? (Asking @allanf181)

**Comment by allanf181** [comment]
:stuck_out_tongue_winking_eye:
- [ ] ~~pass Architect to BRCore~~
- [x] pass to Forged 
- [ ] ~~remove this mod~~

**Comment by NotJustAnna** [comment]
:smile:
So... pass to the Forged Core Modules (embed to Forged.jar) or as a separate Module (Create a Forged-Architect.jar)

**Comment by allanf181** [comment]
Pass to the Forged Core Modules, but with a config.

**Comment by NotJustAnna** [comment]
Ok. Will be passed after release of Forged-1.0
